USE [master]
GO
/****** Object:  Database [ZombieDB]    Script Date: 28/05/2025 9:28:40 p. m. ******/
CREATE DATABASE [ZombieDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ZombieDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ZombieDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ZombieDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ZombieDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ZombieDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ZombieDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ZombieDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ZombieDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ZombieDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ZombieDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ZombieDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ZombieDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ZombieDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ZombieDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ZombieDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ZombieDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ZombieDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ZombieDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ZombieDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ZombieDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ZombieDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ZombieDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ZombieDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ZombieDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ZombieDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ZombieDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ZombieDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ZombieDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ZombieDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ZombieDB] SET  MULTI_USER 
GO
ALTER DATABASE [ZombieDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ZombieDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ZombieDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ZombieDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ZombieDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ZombieDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ZombieDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [ZombieDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ZombieDB]
GO
/****** Object:  Table [dbo].[Eliminados]    Script Date: 28/05/2025 9:28:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Eliminados](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ZombieId] [int] NOT NULL,
	[SimulacionId] [int] NOT NULL,
	[PuntosObtenidos] [int] NOT NULL,
	[Timestamp] [datetime] NOT NULL,
 CONSTRAINT [PK_Eliminados] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Eliminados_Audit]    Script Date: 28/05/2025 9:28:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Eliminados_Audit](
	[EliminadosAudit_Id] [int] IDENTITY(1,1) NOT NULL,
	[Id] [int] NOT NULL,
	[ZombieId] [int] NOT NULL,
	[SimulacionId] [int] NOT NULL,
	[PuntosObtenidos] [int] NOT NULL,
	[Timestamp] [datetime] NOT NULL,
	[DateAudit] [datetime] NOT NULL,
 CONSTRAINT [PK_Eliminados_Audit] PRIMARY KEY CLUSTERED 
(
	[EliminadosAudit_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Simulaciones]    Script Date: 28/05/2025 9:28:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Simulaciones](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[TiempoDisponible] [int] NOT NULL,
	[BalasDisponibles] [int] NOT NULL,
 CONSTRAINT [PK_Simulaciones] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Zombies]    Script Date: 28/05/2025 9:28:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Zombies](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Tipo] [varchar](50) NOT NULL,
	[TiempoDisparo] [int] NOT NULL,
	[BalasNecesarias] [int] NOT NULL,
	[NivelAmenaza] [int] NOT NULL,
 CONSTRAINT [PK_Zombies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Eliminados] ADD  CONSTRAINT [DF_Eliminados_Timestamp]  DEFAULT (getdate()) FOR [Timestamp]
GO
ALTER TABLE [dbo].[Eliminados]  WITH CHECK ADD  CONSTRAINT [FK_Eliminados_Simulaciones] FOREIGN KEY([SimulacionId])
REFERENCES [dbo].[Simulaciones] ([Id])
GO
ALTER TABLE [dbo].[Eliminados] CHECK CONSTRAINT [FK_Eliminados_Simulaciones]
GO
ALTER TABLE [dbo].[Eliminados]  WITH CHECK ADD  CONSTRAINT [FK_Eliminados_Zombies] FOREIGN KEY([ZombieId])
REFERENCES [dbo].[Zombies] ([Id])
GO
ALTER TABLE [dbo].[Eliminados] CHECK CONSTRAINT [FK_Eliminados_Zombies]
GO
USE [master]
GO
ALTER DATABASE [ZombieDB] SET  READ_WRITE 
GO
